/**
 * mutation-check.mjs — do the tests fail when what they guard is broken?
 *
 *   node scripts/mutation-check.mjs            # all mutations
 *   node scripts/mutation-check.mjs M3 M7      # some
 *
 * Each mutation breaks ONE guard with a one-line source change, runs the
 * tests that claim to protect it, and requires them to FAIL. The source is
 * restored in a finally block whatever happens. A mutation the tests do not
 * notice is a hole in the tests, reported as SURVIVED (exit 1).
 *
 * Slow (a minute or two): run before a release and whenever a guard or its
 * tests change. The fast complement is sie/editions/tests/audit-rules.test.mjs.
 *
 * @no-legitimate-corpus
 */
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const T = (f) => `sie/editions/tests/${f}`;

export const MUTATIONS = [
    { id: 'M1', what: 'Free floor (pack stand-off) disabled',
      file: 'sie/editions/edition-turn.js',
      find: "    if (!top.some((e) => packIds.has(e.hypothesis?.scenarioId))) return unchanged;",
      replace: '    return unchanged;',
      tests: [T('edition-adversarial.test.mjs'), T('edition-floor.test.mjs')] },
    { id: 'M2', what: 'generic-word guard disabled',
      file: 'sie/editions/edition-turn.js',
      find: "    if (decision?.action === 'ANSWER' && packIds.has(decision.scenarioId) && genericTokens && genericTokens.size) {",
      replace: '    if (false) {',
      tests: [T('edition-floor.test.mjs')] },
    { id: 'M3', what: 'stand-off rule checks presence 1.0 only',
      file: 'sie/editions/stand-off.js',
      find: 'export const OBSERVED_PRESENCE_MIN = Math.min(...Object.values(BASE_WEIGHT_BY_SOURCE));',
      replace: 'export const OBSERVED_PRESENCE_MIN = 1;',
      tests: [T('stand-off.test.mjs'), T('audit-rules.test.mjs')] },
    { id: 'M4', what: 'content lint accepts everything',
      file: 'sie/editions/pack-guard.js',
      find: '    const reasons = [];\n    const t = String(text ?? \'\').replace(ICONS, \'\');',
      replace: '    return [];\n    const reasons = [];\n    const t = String(text ?? \'\').replace(ICONS, \'\');',
      tests: [T('pack-security.test.mjs'), 'sie/scenarios/tests/scenario-catalog-resolver.test.mjs'] },
    { id: 'M5', what: 'pack guard skips nothing',
      file: 'sie/editions/edition-catalog.js',
      find: '                    const why = checkPackScenario(sc);',
      replace: '                    const why = [];',
      tests: [T('pack-security.test.mjs')] },
    { id: 'M6', what: 'word-set audit rule removed',
      file: 'sie/editions/edition-audit.js',
      find: '                        if (!edRank.isAmbiguous) continue;',
      replace: '                        continue;',
      tests: [T('audit-rules.test.mjs')] },
    { id: 'M7', what: 'console allows Pro smaller than Free',
      file: 'sie/editions/edition-guards.js',
      find: '            if (n < floor) {',
      replace: '            if (false) {',
      tests: [T('edition-guards.test.mjs')] },
    { id: 'M8', what: 'edition message bound not applied in the pipeline',
      file: 'sie/pipeline/pipeline.js',
      find: "glossaryLayers: edition.glossaryLayers || [], maxInputChars: edition.profile.maxMessageChars }",
      replace: 'glossaryLayers: edition.glossaryLayers || [] }',
      tests: [T('edition-turn.test.mjs'), 'sie-integration/tests/editions-bridge.test.mjs'] },
    { id: 'M9', what: 'distinct-evidence-token bound not applied',
      file: 'sie/editions/edition-turn.js',
      find: '            if (kept.size >= max) { dropped += 1; continue; }',
      replace: '',
      tests: [T('edition-turn.test.mjs')] },
    { id: 'M10', what: 'a pack may replace a core scenario by id',
      file: 'sie/editions/edition-catalog.js',
      find: "                        if (seen.has(s.id)) { warnings.push(`Skipped ${name} scenario \"${s.id}\": id already defined by an earlier pack`); continue; }",
      replace: '',
      tests: [T('pack-security.test.mjs')] },
    { id: 'M11', what: 'a synonym may name a token the base does not have',
      file: 'sie/language/normalizer.js',
      find: '            if (isSynonym && !baseCanonicals.has(entry.canonical)) continue;',
      replace: '',
      tests: [T('pack-security.test.mjs')] },
    { id: 'M12', what: 'audit rule synonym_unknown_target removed',
      file: 'sie/editions/edition-audit.js',
      find: "            if (!baseCanonicals.has(e.canonical)) add('synonym_unknown_target', { pack: name, token: e.canonical });",
      replace: '',
      tests: [T('audit-rules.test.mjs')] },
    // Two edits: with only the first, resolved tokens are keyed on their
    // canonical («entity_agent»), which no pattern spells — an inert mutation.
    { id: 'M13', what: 'layers rewrite words the base already resolved',
      file: 'sie/language/normalizer.js',
      edits: [
          { find: '    const open = (t) => t && LAYER_OPEN_SOURCES.has(t.source) && !baseCanonicals.has(t.canonical);',
            replace: '    const open = (t) => !!t;' },
          { find: "                const words = window.map((t) => (t.source === 'unrecognized-latin' ? t.canonical : normalizeArabicToken(t.canonical))).filter(Boolean);",
            replace: "                const words = window.map((t) => (/[\\u0600-\\u06FF]/.test(t.raw) ? normalizeArabicToken(t.raw) : String(t.raw).toLowerCase())).filter(Boolean);" }
      ],
      tests: [T('layers-invariant.test.mjs')] },
    // SQL guards (0010). They need a scratch Postgres: set PGURL, as for
    // scripts/test-migrations.sh; without it they are reported SKIPPED.
    { id: 'M14', what: 'edition write guard lets every session through',
      file: 'sie-integration/migrations/0010_sie_editions_owner_only.sql',
      find: "            then public.sie_owner_authority()\n        else true",
      replace: "            then true\n        else true",
      sql: true },
    { id: 'M15', what: 'owner edition RPC skips the owner check',
      file: 'sie-integration/migrations/0010_sie_editions_owner_only.sql',
      find: "    if not public.sie_owner_authority() then\n        perform public.log_privileged('sie.edition.assign.denied'",
      replace: "    if false then\n        perform public.log_privileged('sie.edition.assign.denied'",
      sql: true },
    { id: 'M16', what: 'a switched-off edition keeps running',
      file: 'sie-integration/migrations/0010_sie_editions_owner_only.sql',
      find: "    return v_raw is null or v_raw = 'true'::jsonb;",
      replace: '    return true;',
      sql: true },
    { id: 'M17', what: 'the self-service guard lets a customer raise their own plan',
      file: 'sie-integration/migrations/0011_sie_self_service.sql',
      find: "       and public.sie_edition_rank(new.edition) < public.sie_edition_rank(public.sie_effective_edition(old.edition)) then",
      replace: "       and true then",
      sql: true },
    { id: 'M18', what: 'the downgrade RPC accepts an upgrade',
      file: 'sie-integration/migrations/0011_sie_self_service.sql',
      find: "    if public.sie_edition_rank(p_target) >= public.sie_edition_rank(v_current) then",
      replace: "    if false then",
      sql: true },
    // ── WP1: the test foundation (docs/REMEDIATION-PLAN-SIE-9-LAYERS.md §5) ──
    // Each breaks one thing WP1 claims to guard; the named tests must fail.
    { id: 'W1-1', what: 'context expiry ignores the injected clock',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        let prevSie = recallPreviousState(botState?.sie || null, settings, now());',
      replace: '        let prevSie = recallPreviousState(botState?.sie || null, settings);',
      tests: ['sie-integration/tests/runtime-clock.test.mjs'] },
    { id: 'W1-2', what: 'lastTurnAt stamped from real time, not the turn clock',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '                lastTurnAt: new Date(now()).toISOString(),',
      replace: '                lastTurnAt: new Date().toISOString(),',
      tests: ['sie-integration/tests/runtime-clock.test.mjs'] },
    { id: 'W1-3', what: 'past-conversation window measured on real time',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '                supabase, userId, sessionId, settings.memory_context_minutes || 1440, now()',
      replace: '                supabase, userId, sessionId, settings.memory_context_minutes || 1440',
      tests: ['sie-integration/tests/runtime-clock.test.mjs'] },
    { id: 'W1-4', what: 'a red regression that now passes is accepted (stale red)',
      file: 'sie-integration/tests/helpers/golden-runner.mjs',
      find: '    if (!ids.length) {',
      replace: '    if (false) {',
      tests: ['sie-integration/tests/golden-runner.test.mjs'] },
    { id: 'W1-5', what: 'a red regression failing for an undeclared reason is accepted',
      file: 'sie-integration/tests/helpers/golden-runner.mjs',
      find: '    if (JSON.stringify(ids) !== JSON.stringify(declared)) {',
      replace: '    if (false) {',
      tests: ['sie-integration/tests/golden-runner.test.mjs'] },
    { id: 'W1-6', what: 'an unknown expectation key passes silently',
      file: 'sie-integration/tests/helpers/golden-runner.mjs',
      find: '            default: throw new Error(`unknown expectation key "${key}"`);',
      replace: '            default: break;',
      tests: ['sie-integration/tests/golden-runner.test.mjs'] },
    { id: 'W1-7', what: 'a guarantee is marked enforced with no evidence',
      file: 'docs/SIE-GUARANTEES.md',
      // (Anchored on G-L1-1 until WP3 enforced it; any still-pending guarantee without evidence serves.)
      find: '| G-L9-6 | L9 | The learning queue includes escalations, declines, withheld actions, re-contact after close and low-specificity tickets. | pending | WP8 | |',
      replace: '| G-L9-6 | L9 | The learning queue includes escalations, declines, withheld actions, re-contact after close and low-specificity tickets. | enforced | — | |',
      tests: ['sie-integration/tests/guarantees.test.mjs'] },
    { id: 'W1-8', what: 'the production profile loses the past-conversation mitigation',
      file: 'sie-integration/tests/fixtures/settings/production.json',
      find: '    "memory_use_past_conversations": false,',
      replace: '    "memory_use_past_conversations": true,',
      tests: ['sie-integration/tests/settings-profiles.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    // Until WP3 this fixed D1 in the bridge's regex classifier, which WP3
    // removed. It now "fixes" F2 (still red, WP4) the same way: the defect
    // goes away and its red regression must notice.
    { id: 'W1-9', what: 'a P0 defect is fixed in the engine but its red regression is not flipped',
      file: 'sie/language/emotion-detector.js',
      find: "            'انا مبسوط جدا بصراحة', 'تحفة بجد', 'عاش يا بطل',",
      replace: "            'تحفة بجد', 'عاش يا بطل',",
      tests: ['sie-integration/tests/golden.test.mjs'] },
    // ── WP2: truthful observability ──
    { id: 'W2-1', what: 'short-circuit routes write no trace again',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '            written = await writeTurnTrace({',
      replace: "            written = rec.route !== 'diagnostic' ? false : await writeTurnTrace({",
      tests: ['sie-integration/tests/observability-truth.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W2-2', what: 'the trace records the intended text instead of the text sent',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        responseText: result?.reply ?? null,',
      replace: '        responseText: rec.intendedText ?? result?.reply ?? null,',
      tests: ['sie-integration/tests/observability-truth.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W2-3', what: 'executed effects dropped from the outcome',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        effects: rec.effects,',
      replace: '        effects: [],',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    { id: 'W2-4', what: 'a created ticket is not recorded as an executed effect',
      file: 'sie-integration/sie-chat-bridge.js',
      find: "        createTicketWithMessageAndSessionUpdate: observe('create_ticket', port.createTicketWithMessageAndSessionUpdate)\n",
      replace: '',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    { id: 'W2-5', what: 'a trusted verdict is left out of the trace',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '            ? (trustTrace(rec.trustEnvelope) ?? { enforced: traceProjection(rec.trustEnvelope), observed: null })',
      replace: '            ? trustTrace(rec.trustEnvelope)',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    { id: 'W2-6', what: 'the live side of the shadow comparison has no kind again',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '                liveResult: { interpretation: { kind: TURN_KINDS.DIAGNOSTIC }, decision: finalDecision, ranking },',
      replace: '                liveResult: { interpretation: null, decision: finalDecision, ranking },',
      tests: ['sie-integration/tests/shadow-comparison.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W2-7', what: 'the shadow decides with default settings, not the live ones',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '                // is a difference in engines, not in thresholds.\n                settings\n',
      replace: '                // is a difference in engines, not in thresholds.\n',
      tests: ['sie-integration/tests/shadow-comparison.test.mjs'] },
    { id: 'W2-8', what: 'a failed trace write is not reported on the result',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        if (turnResult) turnResult.traceWritten = written;',
      replace: '',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    { id: 'W2-9', what: 'a failed trace write is not logged',
      file: 'sie-integration/sie-chat-bridge.js',
      find: "        if (!written && !threw) console.error(`[sie] trace write failed for session ${sessionId}, route ${rec.route ?? 'none'}`);",
      replace: '',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    { id: 'W2-10', what: 'a failed commit is recorded as committed',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        committed: writes.length > 0 && writes[writes.length - 1].ok === true,',
      replace: '        committed: true,',
      tests: ['sie-integration/tests/observability-truth.test.mjs'] },
    // ── WP3: Layer-1 language primitives ──
    { id: 'W3-1', what: 'phrases match as substrings again (G-L1-1)',
      file: 'sie/language/lexicon-match.js',
      find: '            if (w === want) continue;',
      replace: '            if (w.includes(want)) continue;',
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/detector-boundaries.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-2', what: 'negation scopes ignored (G-L1-2)',
      file: 'sie/language/lexicon-match.js',
      find: '        const negated = viaNegatedForm || (negatedAt[i] && !viaConjunction);',
      replace: '        const negated = viaNegatedForm;',
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/negation.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-3', what: 'Egyptian «ما…ش» forms no longer recognised (G-L1-2)',
      file: 'sie/language/lexicon-match.js',
      find: '    return bases.filter((b) => b.length >= 2);',
      replace: '    return [];',
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/negation.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-4', what: 'a clause boundary no longer closes a negation scope (G-L1-2)',
      file: 'sie/language/lexicon-match.js',
      find: '            if (wordClause[k] !== wordClause[j]) break;\n',
      replace: '',
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/negation.test.mjs'] },
    { id: 'W3-5', what: 'a question or condition counts as an assertion (G-L1-2)',
      file: 'sie/language/lexicon-match.js',
      find: "        hits.push({ start: i, end: i + p.length, negated, question, conditional, asserted: !question && !conditional });",
      replace: "        hits.push({ start: i, end: i + p.length, negated, question, conditional, asserted: true });",
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/negation.test.mjs', 'sie/language/tests/precision-corpus.test.mjs'] },
    { id: 'W3-6', what: 'small talk claims the whole message again (G-L1-3)',
      file: 'sie/language/small-talk.js',
      find: '            coversWholeMessage: !diagnosticContent && coversEveryWord(a)',
      replace: '            coversWholeMessage: true',
      tests: ['sie/language/tests/signals.test.mjs', 'sie/language/tests/precision-corpus.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-7', what: 'diagnostic content is never seen (G-L1-3)',
      file: 'sie/language/lexicon-match.js',
      find: '    return Array.isArray(normalizedTokens) && normalizedTokens.some(isDiagnosticToken);',
      replace: '    return false;',
      tests: ['sie/language/tests/lexicon-match.test.mjs', 'sie/language/tests/signals.test.mjs'] },
    { id: 'W3-8', what: 'reply polarity ignores diagnostic content (G-L1-5)',
      file: 'sie/language/reply-polarity.js',
      find: '    if (diagnosticContent || words.length > MAX_SHORT_ANSWER_WORDS) return null;',
      replace: '    if (words.length > MAX_SHORT_ANSWER_WORDS) return null;',
      tests: ['sie/language/tests/reply-polarity.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-9', what: 'a plain «لا» is not a no (G-L1-5, D1)',
      file: 'sie/language/reply-polarity.js',
      find: "    'لا', 'لاء', 'مش',",
      replace: "    'لاء', 'مش',",
      tests: ['sie/language/tests/reply-polarity.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-10', what: 'English "did that solve it?" button no longer reads as resolved (G-L1-4)',
      file: 'sie/language/emotion-detector.js',
      find: "    'resolved', 'solved', 'fixed',",
      replace: "    'solved', 'fixed',",
      tests: ['sie/language/tests/reply-polarity.test.mjs'] },
    { id: 'W3-11', what: 'the bridge classifies the raw text, not what Layer 1 read (G-L1-6)',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '            text: language.rawText,',
      replace: '            text,',
      tests: ['sie-integration/tests/language-signals.test.mjs'] },
    { id: 'W3-12', what: 'truncation dropped from the trace (G-L1-6)',
      file: 'sie/action/supabase-port.supabase.js',
      find: "                ...(traceEvent?.language ? { language: traceEvent.language } : {})\n",
      replace: '',
      tests: ['sie-integration/tests/language-signals.test.mjs'] },
    { id: 'W3-13', what: 'a request to note a problem is a memory capture again (G-L1-7)',
      file: 'sie/language/memory-intent.js',
      find: '    const carriesProblem = (explained) => (Array.isArray(tokens)',
      replace: '    const carriesProblem = (explained) => false && (Array.isArray(tokens)',
      tests: ['sie/language/tests/signals.test.mjs', 'sie/language/tests/precision-corpus.test.mjs'] },
    { id: 'W3-14', what: 'a role marker matches inside a word again (F4)',
      file: 'sie/language/memory-intent.js',
      find: "    return ROLE_WORDS.has(w) || (w.startsWith('ال') && ROLE_WORDS.has(w.slice(2)));",
      replace: "    return [...ROLE_WORDS].some((r) => w.includes(r) && w !== r);",
      tests: ['sie/language/tests/memory-intent.test.mjs', 'sie/language/tests/signals.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-15', what: 'the bridge routes any memory reading to the memory path (F4)',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        const memoryIntent = signals.memory && (signals.memory.explicit || signals.memory.standalone) ? signals.memory : null;',
      replace: '        const memoryIntent = signals.memory;',
      tests: ['sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-16', what: 'the bridge answers a greeting that is not the whole message (F3)',
      file: 'sie-integration/sie-chat-bridge.js',
      find: '        const isPleasantry = smallTalk && smallTalk.coversWholeMessage',
      replace: '        const isPleasantry = smallTalk',
      tests: ['sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-17', what: 'a negated "it worked" reads as resolved (C)',
      file: 'sie/language/emotion-detector.js',
      find: "    return last.negated ? 'unresolved' : 'resolved';",
      replace: "    return 'resolved';",
      tests: ['sie/language/tests/negation.test.mjs', 'sie-integration/tests/golden.test.mjs'] },
    { id: 'W3-18', what: 'a questioned or conditional thanks/satisfaction counts (G-L1-2)',
      file: 'sie/language/emotion-detector.js',
      find: '        const counts = (hit) => !hit.negated && (category.negative || hit.asserted);',
      replace: '        const counts = (hit) => !hit.negated;',
      tests: ['sie/language/tests/negation.test.mjs'] },
    { id: 'W3-19', what: 'typo tolerance on by default (G-L1-9)',
      file: 'sie/language/normalizer.js',
      find: '        typoTolerance = false\n    } = options;',
      replace: '        typoTolerance = true\n    } = options;',
      tests: ['sie/language/tests/typo-integration.test.mjs'] },
    { id: 'W3-20', what: 'typo tolerance corrects known words (G-L1-9)',
      file: 'sie/language/normalizer.js',
      find: '    if (stem.length < TYPO_MIN_STEM || isKnownWord(word, derived)) return null;',
      replace: '    if (stem.length < TYPO_MIN_STEM) return null;',
      tests: ['sie/language/tests/typo-integration.test.mjs'] },
    { id: 'W3-21', what: 'typo tolerance may produce any canonical (G-L1-9)',
      file: 'sie/language/normalizer.js',
      find: 'const TYPO_TARGET = /^(entity|symptom|intent|http|qualifier|atom)_/;',
      replace: 'const TYPO_TARGET = /./;',
      tests: ['sie/language/tests/typo-integration.test.mjs'] },
    { id: 'W3-22', what: 'typo tolerance accepts an ambiguous best match (G-L1-9)',
      file: 'sie/language/normalizer.js',
      find: '    return best && !ambiguous ? best.canonical : null;',
      replace: '    return best ? best.canonical : null;',
      tests: ['sie/language/tests/typo-integration.test.mjs'] },
    { id: 'W3-23', what: 'typo evidence weighs as much as an exact match (G-L1-9)',
      file: 'sie/diagnostics/evidence-extractor.js',
      find: '    typo: 0.75\n',
      replace: '    typo: 1.0\n',
      tests: ['sie/language/tests/typo-integration.test.mjs'] },
    { id: 'M19', what: 'the entitlement reports the assigned plan, not the effective one',
      file: 'sie-integration/migrations/0011_sie_self_service.sql',
      find: "    v_edition := public.sie_effective_edition(v_row.edition);\n    v_cap",
      replace: "    v_edition := coalesce(v_row.edition, 'max');\n    v_cap",
      sql: true }
];

function run(m) {
    const file = path.join(ROOT, m.file);
    const original = fs.readFileSync(file, 'utf8');
    const edits = m.edits || [{ find: m.find, replace: m.replace }];
    for (const e of edits) {
        const count = original.split(e.find).length - 1;
        if (count !== 1) return { ...m, verdict: 'STALE', detail: `anchor found ${count}× — update the mutation` };
    }
    if (m.sql && !process.env.PGURL) return { ...m, verdict: 'SKIPPED', detail: 'set PGURL to a scratch Postgres' };
    const tests = m.sql ? ['scripts/test-migrations.sh'] : m.tests.filter((t) => fs.existsSync(path.join(ROOT, t)));
    try {
        fs.writeFileSync(file, edits.reduce((src, e) => src.replace(e.find, () => e.replace), original));
        const r = m.sql
            ? spawnSync('bash', tests, { cwd: ROOT, encoding: 'utf8', timeout: 600000, env: process.env })
            : spawnSync(process.execPath, ['--test', ...tests], { cwd: ROOT, encoding: 'utf8', timeout: 600000 });
        if (m.sql) return { ...m, tests, verdict: r.status !== 0 ? 'KILLED' : 'SURVIVED', detail: (r.stdout.match(/(FAIL|ERROR)[^\n]*/) || ['no FAIL line'])[0].slice(0, 90) };
        const failed = (r.stdout.match(/^# fail (\d+)/m) || [])[1];
        return { ...m, tests, verdict: r.status !== 0 ? 'KILLED' : 'SURVIVED', detail: `${failed ?? '?'} failing` };
    } finally {
        fs.writeFileSync(file, original);
    }
}

if (import.meta.url === `file://${process.argv[1]}`) {
    const pick = process.argv.slice(2);
    const rows = [];
    for (const m of MUTATIONS.filter((x) => !pick.length || pick.includes(x.id))) {
        const r = run(m);
        rows.push(r);
        console.log(`${r.verdict.padEnd(8)} ${r.id.padEnd(4)} ${r.what} — ${r.detail}${r.tests ? ` [${r.tests.map((t) => path.basename(t)).join(', ')}]` : ''}`);
    }
    process.exit(rows.some((r) => r.verdict !== 'KILLED' && r.verdict !== 'SKIPPED') ? 1 : 0);
}
